### ISSUE TITLE
1주차

### ISSUE THREAD

**Issue by alsco1234** [22000217/OSSL_teamProject#1]
1. 개인 repo 생성
2. 서로 소개 pr 연습
3. 팀 프로젝트 repo 생성
4. issue 생성하여 의논
5. 주제선정 밑 위키정리
6. 설계
7. README 작성

**Comment by nayeawon** [comment]
**아이디어**

1. 옷 브랜드
옷 종류로 linked list 나눠서 구현
(상의, 하의, 원피스, 아우터)
2. 백신 접종 여부 / 검사 여부
ex) 검사받아야하는 사람or백신 접종 대상자 추가, 업데이트 -> 삭제 -> 파일에 저장
3. 실종자 관리
4. 날씨 기상예보
5. Task Manager

**Comment by alsco1234** [comment]
학관 메뉴 관리 프로그램
: 든든한동등 여러 학관 음식점 메뉴 정리
구조체 : 메뉴 / 가격

C : 메뉴 추가
R : 메뉴 읽기
U : 메뉴 수정
D : 메뉴 삭제

**Comment by nayeawon** [comment]
옷 브랜드

-> 옷 브랜드 목록을 보여주고 원하는 쇼핑몰을 선택 -> 해당 쇼핑몰의 옷들 중에서 상의, 하의, 원피스, 아우터 중에서 또 선택
-> A 브랜드 쇼핑몰의 상의를 선택했다고 하면, 거기에서 CRUD 함수 구현

**Comment by alsco1234** [comment]
+ linked list를 이용, 다음 옷을 연결

**Comment by alsco1234** [comment]
int createClothes(Clothes *c) //Create : 카테고리 맞는 새 구조체 생성
void readClothes(Clothes *c) 
void listClothes(Clothes *c, int count) // Read : 카테고리 맞는 구조체들 읽어오기
int updateClothes(Clothes *c) //Update : 대상 구조체 수정
int deleteClothes(Clothes *c) //Delete : 대상 구조체 삭제

**Comment by alsco1234** [comment]
void saveData(Clothes *c, int count); //데이터 저장
int loadData(Clothes *c); //데이터 읽어오기

**Comment by alsco1234** [comment]
> int createClothes(Clothes *c) //Create : 카테고리 맞는 새 구조체 생성
> void readClothes(Clothes *c)
> void listClothes(Clothes *c, int count) // Read : 카테고리 맞는 구조체들 읽어오기
> int updateClothes(Clothes *c) //Update : 대상 구조체 수정
> int deleteClothes(Clothes *c) //Delete : 대상 구조체 삭제

이거 구조체 다 다르게 할거면 함수도 각자 하나씩 만들어야하나?

**Comment by alsco1234** [comment]
> void saveData(Clothes *c, int count); //데이터 저장
> int loadData(Clothes *c); //데이터 읽어오기

저장은 카테고리별로 다른 파일? 한 파일에 카테고리별 정리?

**Comment by nayeawon** [comment]
> > int createClothes(Clothes *c) //Create : 카테고리 맞는 새 구조체 생성
> > void readClothes(Clothes *c)
> > void listClothes(Clothes *c, int count) // Read : 카테고리 맞는 구조체들 읽어오기
> > int updateClothes(Clothes *c) //Update : 대상 구조체 수정
> > int deleteClothes(Clothes *c) //Delete : 대상 구조체 삭제
> 
> 이거 구조체 다 다르게 할거면 함수도 각자 하나씩 만들어야하나?

**Comment by nayeawon** [comment]
typedef struct {
    char name[30]; // 제품명
    int price; // 가격
    char size; // 사이즈
    int review; // 리뷰개수
    int num_stars;  //  별점개수
    top *link;    //  다음 node를 가리키는 포인터 변수 n
}top;

typedef struct {
    char name[30]; // 제품명
    int price; // 가격
    int length; //  총길이
    char size; // 사이즈(S, M, L, F(Free))
    int review; // 리뷰개수
    int num_stars;  //  별점개수
    bottom *link;    //  다음 node를 가리키는 포인터 변수 n
}bottom;

typedef struct {
    char name[30]; // 제품명
    int price; // 가격
    char size;  // 사이즈
    int review; // 리뷰개수
    int num_stars;  //  별점개수
    dress *link;    //  다음 node를 가리키는 포인터 변수 n
}dress;

지금 여기까지 짜봤는데 옷 종류마다 구조체 멤버가 그냥 다 똑같아서 굳이 구조체 다르게 할 필요가 없는 거 같아

**Comment by alsco1234** [comment]
> > void saveData(Clothes *c, int count); //데이터 저장
> > int loadData(Clothes *c); //데이터 읽어오기
> 
> 저장은 카테고리별로 다른 파일? 한 파일에 카테고리별 정리?

-> 텍스트파일은 카테고리별로 다 따로!

**Comment by alsco1234** [comment]
`int createClothes(Clothes *c) //Create : 카테고리 맞는 새 구조체 생성
void readClothes(Clothes *c)
void listClothes(Clothes *c, int count) // Read : 카테고리 맞는 구조체들 읽어오기
int updateClothes(Clothes *c) //Update : 대상 구조체 수정
int deleteClothes(Clothes *c) //Delete : 대상 구조체 삭제`

**Comment by nayeawon** [comment]
# 구조체 정의
typedef struct {
    char name[30]; // 제품명
    int price; // 가격
    char size; // 사이즈(S, M, L, F(Free))
    int review; // 리뷰개수
    int num_stars;  //  별점개수
    Clothes *link;    //  다음 node를 가리키는 포인터 변수 n
}Clothes;

**Comment by alsco1234** [comment]
searchName(Clothes *c, int count)
searchPrice(Clothes *c, int count)
searchSize(Clothes *c, int count)
searchNum_stars(Clothes *c, int count)

**Comment by alsco1234** [comment]
깃헙 관리 + CRUD + 파일읽기 + 툴짜기 / 테스터 + 검색 + 파일저장 + 자료조사
