### ISSUE TITLE
수정요청 1) 다중데이터의 Delete

### ISSUE THREAD

**Issue by alsco1234** [22000217/OSSL_teamProject#10]
![image](https://user-images.githubusercontent.com/80326391/117655166-b05b8080-b1d1-11eb-8cd1-3366e9d2013e.png)

보는 것과 같이 다중데이터가 있을 때, 이전의 데이터를 선택하면 실행이 멈춰버리는 에러가 있습니다!

아래는 오류가 났던 테스트 전문입니다.
[1]목록 [2]추가 [3]수정 [4]삭제 [0]종료 >> 2

제품명? 봄원피스
가격? 20000
사이즈 (S, M, L, F(Free)? S
리뷰개수? 20
별점개수? 30
카테고리 (0:상의, 1:하의, 2:드레스, 3:전체)? 2
==> 추가됨

[1]목록 [2]추가 [3]수정 [4]삭제 [0]종료 >> 2

제품명? 여름원피스
가격? 50000
사이즈 (S, M, L, F(Free)? L
리뷰개수? 50
별점개수? 40
카테고리 (0:상의, 1:하의, 2:드레스, 3:전체)? 2
==> 추가됨

[1]목록 [2]추가 [3]수정 [4]삭제 [0]종료 >> 1
카테고리 (0:상의, 1:하의, 2:드레스, 3:전체)? 2
제품 정보입니다.
봄원피스 S  20000
여름원피스 L  50000
........(총 2개)

[1]목록 [2]추가 [3]수정 [4]삭제 [0]종료 >> 3
카테고리 (0:상의, 1:하의, 2:드레스, 3:전체)? 2
봄원피스 S  20000  
여름원피스 L  50000
........(총 2개)   
수정하고 싶은 제품 이름? 여름원피스

제품명? 여름원피스2
가격? 25000
사이즈 (S, M, L, F(Free)? L
리뷰개수? 30
별점개수? 2
==> 수정됨

[1]목록 [2]추가 [3]수정 [4]삭제 [0]종료 >> 1
카테고리 (0:상의, 1:하의, 2:드레스, 3:전체)? 2
제품 정보입니다.
봄원피스 S  20000
여름원피스2 L  25000
........(총 2개)

[1]목록 [2]추가 [3]수정 [4]삭제 [0]종료 >> 4
카테고리 (0:상의, 1:하의, 2:드레스, 3:전체)? 2
봄원피스 S  20000
여름원피스2 L  25000
........(총 2개)
삭제하고 싶은 제품 이름? 봄원피스

**Comment by nayeawon** [comment]
ERROR 수정완료
