### ISSUE TITLE
수정요청 2) 띄어쓰기가 있는 제품명의 Create

### ISSUE THREAD

**Issue by alsco1234** [22000217/OSSL_teamProject#11]
![image](https://user-images.githubusercontent.com/80326391/117655408-ff091a80-b1d1-11eb-8f95-800700c45ef5.png)

보이는 것과 같이 제품명에 띄어쓰기가 있을 때 오류가 생깁니다.

아래는 오류가 난 테스트 전문입니다.
[1]목록 [2]추가 [3]수정 [4]삭제 [0]종료 >> 2

제품명? 봄 원피스
가격? 사이즈 (S, M, L, F(Free)? 리뷰개수? 1200
별점개수? 3
카테고리 (0:상의, 1:하의, 2:드레스, 3:전체)? 0
==> 추가됨

[1]목록 [2]추가 [3]수정 [4]삭제 [0]종료 >> 1
카테고리 (0:상의, 1:하의, 2:드레스, 3:전체)? 0
제품 정보입니다.
봄 원피스  1984351424
........(총 1개)

[1]목록 [2]추가 [3]수정 [4]삭제 [0]종료 >> 0
종료되었습니다.

**Comment by nayeawon** [comment]
수정완료 하였습니다 :)
