### ISSUE TITLE
검색시 카테고리 분류?

### ISSUE THREAD

**Issue by alsco1234** [22000217/OSSL_teamProject#19]
처음에는 검색시 검색할 카테고리를 입력받고, 카테고리 내에서 이름/사이즈 등으로 검색하려 했으나

data의 수가 적고 검색이라는 기능을 생각해봤을 때 여러 카테고리가 한꺼번에 나오는게 좋을 것 같아
카테고리별로 분류해서 보여주되, 한 카테고리만 보게 하지는 않으려고 합니다.

어떻게 생각하시나요?

**Comment by nayeawon** [comment]
좋은 것 같습니다!!
