### ISSUE TITLE
Load함수의 vector

### ISSUE THREAD

**Issue by alsco1234** [22000217/OSSL_teamProject#21]
load함수에서 vector을 이용하여 추가하셨었는데,
제가 vector 사용법을 잘 몰라서 다른 방법을 사용하였습니다!

**Comment by nayeawon** [comment]
load함수는 제가 코딩하기로 했던거 아니였나요....?

**Comment by alsco1234** [comment]
저 바보짓한 것 같네요..내일까지 다시 수정하겠습니다.. 백업파일은 있어여ㅠㅠㅠ 죄송합니다

**Comment by nayeawon** [comment]
아아 그럼 머지 안하고 제꺼에서 한번에 수정해서 커밋하겠습니당!! 아직 제가 pull을 안했어요

**Comment by nayeawon** [comment]
pull 안하고 수정하기에는 무리가 있는 거 같아서 머지했습니다

**Comment by alsco1234** [comment]
감사합니다!
