### ISSUE TITLE
load 전체 불러오기

### ISSUE THREAD

**Issue by alsco1234** [22000217/OSSL_teamProject#25]
![image](https://user-images.githubusercontent.com/80326391/118642766-b0cdca00-b816-11eb-9e55-5b68bc1877e3.png)
전체 불러오기시 error가 뜨는데, 의도하신건가요?

**Comment by nayeawon** [comment]
네 그거 예외처리 해놨어요!!

**Comment by alsco1234** [comment]
확인했습니다!
