### ISSUE TITLE
2주차 

### ISSUE THREAD

**Issue by alsco1234** [22000217/OSSL_teamProject#4]
- 검색 기능 및 파일 저장, 읽어보기 기능을 제외한 모든 함수 구현 및 git으로 버전 관리
- 완성된 각 함수를 실행한 화면캡처 업로드 (github repository root에서 /screenshots 폴더 만들어서 이미지 업로드)
- issue를 사용하여 개발에 필요한 의견 교환
- WIKI에서 완성된 함수 설명 및 결과 이미지를 이용한 페이지 추가(md 페이지 추가)

**Comment by alsco1234** [comment]
linked list를 사용하는데, 사용 언어는 c인가요? c++인가요?

**Comment by alsco1234** [comment]
관리자용 프로그램을 만들고 있는데, 리뷰 개수와 별점은 단순히 결과를 입력받고 처리만 하면 되나요? 아니면 리뷰를 입력받고 리뷰개수와 별점을 수정하는 기능까지 필요할까요?

**Comment by nayeawon** [comment]
> linked list를 사용하는데, 사용 언어는 c인가요? c++인가요?

저는 어떤 언어로 해도 상관없습니다 무슨 언어가 더 편하신가요?

> 관리자용 프로그램을 만들고 있는데, 리뷰 개수와 별점은 단순히 결과를 입력받고 처리만 하면 되나요? 아니면 리뷰를 입력받고 리뷰개수와 별점을 수정하는 기능까지 필요할까요?

단순히 결과를 입력받고 처리하는 걸로 생각했었는데, 말한 것처럼 리뷰를 입력받고 수정하는 기능을 추가해도 좋을 거 같네요

**Comment by nayeawon** [comment]
코드 짜신 거 보니까 C로 하셨던데, 제가 C++로도 한번 짜볼게요
Delete 함수는 삭제할 제품 이름을 입력받고 그에 해당되는 걸 삭제하도록 짤까요?

**Comment by nayeawon** [comment]
참고 코드))
c->get_name().find(p_name)>=0

**Comment by nayeawon** [comment]
CRUD C++로 구현완료, 테스트 필요
